"""Add_workspace_settings

Revision ID: 366c8843d3a3
Revises: 01e5d123e065
Create Date: 2026-02-10 18:29:47.322379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366c8843d3a3'
down_revision: Union[str, Sequence[str], None] = '01e5d123e065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'settings')
    # ### end Alembic commands ###
